#!/usr/bin/env python
#
#

import urllib2
import json
import sys
import os

from optparse import OptionParser

parser = OptionParser()
parser.add_option("-t", "--everynet-api-token", dest="token")
parser.add_option("-g", "--gateway_mac", dest="gw_mac")

(options, args) = parser.parse_args()

if not options.gw_mac:
    print 'ERROR no gateway mac address name provided'
    sys.exit(3)

token = os.getenv('EVERYNET_API_TOKEN', None)
if token == None and options.token:
    token = options.token

if token == None:
    print 'ERROR no everynet api token provided'
    sys.exit(3)


# query everynet api for the given gw
url = 'https://api.everynet.com/1.0/monitoring/gateways/%s' % options.gw_mac
request = urllib2.Request(url)
request.add_header('Authorization',token)

contents = urllib2.urlopen(request).read()

data = json.loads(contents)

if 'DeviceDown' in data['gateway'] or 'GatewayDown' in data['gateway']:
    print 'CRITICAL Gateway {} down'.format(options.gw_mac)
    sys.exit(2)
else:
    print 'OK Gateway {} online'.format(options.gw_mac)
    sys.exit(0)

print 'WARNING Unknow status for {} '.format(options.gw_mac)
sys.exit(1)
